### ISSUE TITLE
Android app

### ISSUE THREAD

**Issue by fragtion** [seniorglez/Casio-LikeCalculatorLib#2]
Hi

Great work with this

Do you have source code for the actual app as shown in the project screenshot ? Not just the library ... Tnx

**Comment by seniorglez** [comment]
Hi @fragtion ! 
I am very sorry I did not respond earlier (I had disabled the notifications on this project).  I started making this library with the hope that it would serve to facilitate making a calculator for people who want to learn to build interfaces for Android but I stopped working on it when I had to focus on other languages. Anyway, I will try to build a demo for you this evening.

**Comment by seniorglez** [comment]
I've adapted the [original project](https://github.com/seniorglez/CommunistCalculator) so it uses the library. 

Using it is very simple you only have to import the jar as in any android project and add the following to the build.gradle file:

```
    android {
       compileOptions {
           sourceCompatibility JavaVersion.VERSION_1_8
           targetCompatibility JavaVersion.VERSION_1_8
    }
}
```
If you still need to use it, tell me if it works in your project!  :v:

**Comment by fragtion** [comment]
Hi bro. Will give this a shot, looks awesome. thanks!!

**Comment by seniorglez** [comment]
I'm glad you like it!
